spring.datasource.url=jdbc:postgresql://localhost:5432/quartz-scheduler
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.quartz.job-store-type=jdbc

spring.quartz.jdbc.initialize-schema=never

spring.quartz.properties.org.quartz.scheduler.instanceName=MyScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.dataSource=myDS
spring.quartz.properties.org.quartz.dataSource.myDS.driver=org.postgresql.Driver
spring.quartz.properties.org.quartz.dataSource.myDS.URL=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quartz-scheduler}
spring.quartz.properties.org.quartz.dataSource.myDS.user=user
spring.quartz.properties.org.quartz.dataSource.myDS.password=password
spring.quartz.properties.org.quartz.dataSource.myDS.maxPoolSize=5

spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.useProperties=false